title: "William E. J. Carter — UX & Content Strategy"
name: "William E. J. Carter"
url: "www.humanfirstux.work"
baseurl: "/william-carter-portfolio"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "William E. J. Carter"
  avatar: "/assets/images/headshot.jpg"
  bio: "UX & Content Strategist focused on clarity, accessibility, and measurable results."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "www.linkedin.com/in/william-carter-65518059"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Fastlikelava/william-carter-portfolio"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:wcarter8128@gmail.com"

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      classes: wide

collections:
  work:
    output: true

locale: "en-US"
description: "Portfolio of William E. J. Carter — UX & Content Strategy leader transforming complex services into simple, accessible digital experiences."
